version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
        POSTGRES_DB: dev
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
      - "15432:5432"
    volumes:
      - C:/Users/vrdsv/go/src/toDoListGo/data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/toDoListGo
    ports:
      - "8080:8080"
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
